services:
  - type: web
    name: gnostic-oracle
    runtime: python
    repo: https://github.com/Nesermesi/gnostic-oracle
    plan: free
    region: frankfurt
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app
    autoDeploy: true
version: "1"
